# 基本配置
linfeng:
  # 项目名称
  name: linfengBlog2
  # 项目版本
  version: 2.0

# 开发环境
server:
  # 服务器端口号
  port: 80
  servlet:
    # 应用访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数
    accept-count: 200
    threads:
      # tomcat最大线程数
      max: 400
      # Tomcat初始化线程数
      min-spare: 50

# spring配置
spring:
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 5MB
      # 总上传文件大小
      max-request-size: 20MB
