# 基本配置
linfeng:
  # 项目名称
  name: linfengBlog2
  # 项目版本
  version: 2.0

# 开发环境
server:
  # 服务器端口号
  port: 12666
  servlet:
    # 应用访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数
    accept-count: 200
    threads:
      # tomcat最大线程数
      max: 400
      # Tomcat初始化线程数
      min-spare: 50

# spring配置
spring:
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 5MB
      # 总上传文件大小
      max-request-size: 20MB
  # 配置数据源
  datasource:
    # MySQL驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url
    url: jdbc:mysql://localhost:3306/linfeng_blog_two?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    # 用户名
    username: blog
    # 密码
    password: blog

mybatis:
  #起别名
  type-aliases-package: vip.linfeng.pojo
  #扫描所有的mybatis的xml文件
  mapper-locations: classpath:mybatis/*.xml
